server:
  port: 8080

spring:
  application:
    name: marketiniya-vault
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin}
  cache:
    type: simple

google:
  cloud:
    project-id: ${GOOGLE_CLOUD_PROJECT_ID:311217329392}

vault:
  api:
    key: ${VAULT_API_KEY:AIzaSyANdTLYwZklh7u3rb9g-o32q44J6mDOWsk}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.marketiniya.vault: INFO
    com.google.cloud: WARN
