package com.marketiniya.vault.constants;

public final class SecretNames {
    // PROD WEB Firebase secrets
    public static final String MARKETINYA_PROD_WEB_FIREBASE_API_KEY = "MARKETINYA_PROD_WEB_FIREBASE_API_KEY";
    public static final String MARKETINYA_PROD_WEB_FIREBASE_APP_ID = "MARKETINYA_PROD_WEB_FIREBASE_APP_ID";
    public static final String MARKETINYA_PROD_WEB_FIREBASE_AUTH_DOMAIN = "MARKETINYA_PROD_WEB_FIREBASE_AUTH_DOMAIN";
    public static final String MARKETINYA_PROD_WEB_FIREBASE_MESSAGING_SENDER_ID = "MARKETINYA_PROD_WEB_FIREBASE_MESSAGING_SENDER_ID";
    public static final String MARKETINYA_PROD_WEB_FIREBASE_PROJECT_ID = "MARKETINYA_PROD_WEB_FIREBASE_PROJECT_ID";
    public static final String MARKETINYA_PROD_WEB_FIREBASE_STORAGE_BUCKET = "MARKETINYA_PROD_WEB_FIREBASE_STORAGE_BUCKET";

    // WIP WEB Firebase secrets
    public static final String MARKETINYA_WIP_WEB_FIREBASE_API_KEY = "MARKETINYA_WIP_WEB_FIREBASE_API_KEY";
    public static final String MARKETINYA_WIP_WEB_FIREBASE_APP_ID = "MARKETINYA_WIP_WEB_FIREBASE_APP_ID";
    public static final String MARKETINYA_WIP_WEB_FIREBASE_AUTH_DOMAIN = "MARKETINYA_WIP_WEB_FIREBASE_AUTH_DOMAIN";
    public static final String MARKETINYA_WIP_WEB_FIREBASE_MEASUREMENT_ID = "MARKETINYA_WIP_WEB_FIREBASE_MEASUREMENT_ID";
    public static final String MARKETINYA_WIP_WEB_FIREBASE_MESSAGING_SENDER_ID = "MARKETINYA_WIP_WEB_FIREBASE_MESSAGING_SENDER_ID";
    public static final String MARKETINYA_WIP_WEB_FIREBASE_PROJECT_ID = "MARKETINYA_WIP_WEB_FIREBASE_PROJECT_ID";
    public static final String MARKETINYA_WIP_WEB_FIREBASE_STORAGE_BUCKET = "MARKETINYA_WIP_WEB_FIREBASE_STORAGE_BUCKET";
}
