package com.marketiniya.vault.model;

import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_NULL)
public record SecretsResponse(
    // PROD WEB Firebase secrets
    String MARKETINYA_PROD_WEB_FIREBASE_API_KEY,
    String MARKETINYA_PROD_WEB_FIREBASE_APP_ID,
    String MARKETINYA_PROD_WEB_FIREBASE_AUTH_DOMAIN,
    String MARKETINYA_PROD_WEB_FIREBASE_MESSAGING_SENDER_ID,
    String MARKETINYA_PROD_WEB_FIREBASE_PROJECT_ID,
    String MARKETINYA_PROD_WEB_FIREBASE_STORAGE_BUCKET,
    
    // WIP WEB Firebase secrets
    String MARKETINYA_WIP_WEB_FIREBASE_API_KEY,
    String MARKETINYA_WIP_WEB_FIREBASE_APP_ID,
    String MARKETINYA_WIP_WEB_FIREBASE_AUTH_DOMAIN,
    String MARKETINYA_WIP_WEB_FIREBASE_MEASUREMENT_ID,
    String MARKETINYA_WIP_WEB_FIREBASE_MESSAGING_SENDER_ID,
    String MARKETINYA_WIP_WEB_FIREBASE_PROJECT_ID,
    String MARKETINYA_WIP_WEB_FIREBASE_STORAGE_BUCKET
) {}
